apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels: 
    tier: frontend
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
           - containerPort: 80
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypassword
          ports:
            - containerPort: 3306