apiVersion: v1
kind: Service 
metadata: 
  name: myapp-service
spec:
  selector:
    app: nginx
    tier: frontend
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
     